FROM python:3.10

WORKDIR /app

COPY requirements.txt .

# RUN apt-get update && apt-get install -y libpq-dev

RUN pip install --no-cache-dir -r requirements.txt

COPY streams_insert.py .

CMD [ "python", "streams_insert.py" ]
